title: OSVQ
subtitle: "I'm baby prism edison bulb you probably haven't heard of them, blue bottle YOLO messenger bag kogi swag."
idGCalendar: 'xxxxxxxxxxxxxxxxxxxxxxxxxx@group.calendar.google.com'
googleAnalytics: 'UA-xxxxxxxxx-x'
valideTags: 
    - afterwork
    - petitdej
    - networking
    - tech
    - formation
    - workshop
    - socialmedia
    - entrepreneuriat